"""Add agent_run_id to itineraries for idempotency

Revision ID: bcce80626c75
Revises: 1d8750e332d8
Create Date: 2026-09-12 01:58:28.870365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcce80626c75'
down_revision: Union[str, None] = '1d8750e332d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('agent_run_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'itineraries', 'agent_runs', ['agent_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itineraries', type_='foreignkey')
    op.drop_column('itineraries', 'agent_run_id')
    # ### end Alembic commands ###
